const initialContact = {
  _id: "",
  address: "",
  email: "",
  iscompany: false,
  iscustomer: true,
  jobtitle: "",
  mobile: "",
  name: "",
  phone: "",
  status: true,
  title: "",
  website: "",
  companyref: null,
  government: "",
  area: "",
  taxesnumber: "",
  serial: "",
  registrationnumber: "",
  maxdebitlimit: 0.0,
  invoicedueperiod: 0,
  discountpercentage: 0,
  paymentpolicy: "",
  islocal: false,
  isglobal: false,
  invoicetimestable: [],
  chequetimestable: [],
};

const initialSearch = {
  name: "",
  nameisused: false,
  mobile: "",
  mobileisused: false,
  email: "",
  emailisused: false,
  type: null,
  iscustomer: false,
  iscustomerisused: false,
  statustype: null,
  status: false,
  statusisused: false,
  serial: "",
  serialnumberisused: false,
  ownertype: null,
  iscompany: false,
  iscompanyisused: false,
  islocal: false,
  islocalisused: false,
  isglobal: false,
  isglobalisused: false,
};
export { initialContact, initialSearch };
